# Generated by Django 3.2 on 2021-04-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_rename_donate_donater'),
    ]

    operations = [
        migrations.AddField(
            model_name='donater',
            name='Doner_address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
